// Generated by CoffeeScript 1.10.0
(function() {
  var EmptyStringError, OpaqueStringProfile, precis;

  EmptyStringError = require('../error/EmptyStringError');

  precis = require('../constants');

  module.exports = OpaqueStringProfile = (function() {
    function OpaqueStringProfile() {}

    OpaqueStringProfile.prototype.stringClass = precis.STRING_CLASS.FREEFORM;

    OpaqueStringProfile.prototype.widthMapping = precis.WIDTH_MAPPING.NONE;

    OpaqueStringProfile.prototype.caseMapping = precis.CASE_MAPPING.NONE;

    OpaqueStringProfile.prototype.normalization = precis.NORMALIZATION.C;

    OpaqueStringProfile.prototype.directionality = precis.DIRECTIONALITY.NONE;

    OpaqueStringProfile.prototype.map = function(codepoints, propertyReader) {
      var codepoint, i, j, len, results;
      results = [];
      for (i = j = 0, len = codepoints.length; j < len; i = ++j) {
        codepoint = codepoints[i];
        if (propertyReader.isNonAsciiSpace(codepoint)) {
          results.push(codepoints[i] = 0x20);
        } else {
          results.push(void 0);
        }
      }
      return results;
    };

    OpaqueStringProfile.prototype.validate = function(codepoints) {
      if (codepoints.length < 1) {
        throw new EmptyStringError();
      }
    };

    return OpaqueStringProfile;

  })();

}).call(this);
