// Generated by CoffeeScript 1.9.3
(function() {
  var EmptyStringError, OpaqueStringProfile, Precis;

  EmptyStringError = require('../error/EmptyStringError');

  Precis = require('../constants');

  module.exports = OpaqueStringProfile = (function() {
    function OpaqueStringProfile() {}

    OpaqueStringProfile.prototype.stringClass = Precis.STRING_CLASS.FREEFORM;

    OpaqueStringProfile.prototype.widthMapping = Precis.WIDTH_MAPPING.NONE;

    OpaqueStringProfile.prototype.caseMapping = Precis.CASE_MAPPING.NONE;

    OpaqueStringProfile.prototype.normalization = Precis.NORMALIZATION.C;

    OpaqueStringProfile.prototype.directionality = Precis.DIRECTIONALITY.NONE;

    OpaqueStringProfile.prototype.map = function(codepoints, propertyReader) {
      var codepoint, i, j, len, results;
      results = [];
      for (i = j = 0, len = codepoints.length; j < len; i = ++j) {
        codepoint = codepoints[i];
        if (propertyReader.isNonAsciiSpace(codepoint)) {
          results.push(codepoints[i] = 0x20);
        } else {
          results.push(void 0);
        }
      }
      return results;
    };

    OpaqueStringProfile.prototype.validate = function(codepoints) {
      if (codepoints.length < 1) {
        throw new EmptyStringError();
      }
    };

    return OpaqueStringProfile;

  })();

}).call(this);
