// Generated by CoffeeScript 1.9.3
(function() {
  var EmptyStringError, Precis, UsernameCaseMappedProfile;

  EmptyStringError = require('../error/EmptyStringError');

  Precis = require('../constants');

  module.exports = UsernameCaseMappedProfile = (function() {
    function UsernameCaseMappedProfile() {}

    UsernameCaseMappedProfile.prototype.stringClass = Precis.STRING_CLASS.IDENTIFIER;

    UsernameCaseMappedProfile.prototype.widthMapping = Precis.WIDTH_MAPPING.EAW;

    UsernameCaseMappedProfile.prototype.caseMapping = Precis.CASE_MAPPING.LOWERCASE;

    UsernameCaseMappedProfile.prototype.normalization = Precis.NORMALIZATION.C;

    UsernameCaseMappedProfile.prototype.directionality = Precis.DIRECTIONALITY.BIDI;

    UsernameCaseMappedProfile.prototype.validate = function(codepoints) {
      if (codepoints.length < 1) {
        throw new EmptyStringError();
      }
    };

    return UsernameCaseMappedProfile;

  })();

}).call(this);
