// Generated by CoffeeScript 1.9.3
(function() {
  var EmptyStringError, UsernameCasePreservedProfile, precis;

  EmptyStringError = require('../error/EmptyStringError');

  precis = require('../constants');

  module.exports = UsernameCasePreservedProfile = (function() {
    function UsernameCasePreservedProfile() {}

    UsernameCasePreservedProfile.prototype.stringClass = precis.STRING_CLASS.IDENTIFIER;

    UsernameCasePreservedProfile.prototype.widthMapping = precis.WIDTH_MAPPING.EAW;

    UsernameCasePreservedProfile.prototype.caseMapping = precis.CASE_MAPPING.NONE;

    UsernameCasePreservedProfile.prototype.normalization = precis.NORMALIZATION.C;

    UsernameCasePreservedProfile.prototype.directionality = precis.DIRECTIONALITY.BIDI;

    UsernameCasePreservedProfile.prototype.validate = function(codepoints) {
      if (codepoints.length < 1) {
        throw new EmptyStringError();
      }
    };

    return UsernameCasePreservedProfile;

  })();

}).call(this);
