// Generated by CoffeeScript 1.9.3
(function() {
  var WidthMapper;

  module.exports = WidthMapper = (function() {
    function WidthMapper(data) {
      var codepoint, i, j, len;
      this._index = {};
      for (i = j = 0, len = data.length; j < len; i = j += 2) {
        codepoint = data[i];
        this._index[codepoint] = data[i + 1];
      }
    }

    WidthMapper.prototype.map = function(codepoints) {
      var i, results;
      i = codepoints.length - 1;
      results = [];
      while (i >= 0) {
        if (this._index.hasOwnProperty(codepoints[i])) {
          codepoints.splice(i, 1, this._index[codepoints[i]]);
        }
        results.push(--i);
      }
      return results;
    };

    return WidthMapper;

  })();

}).call(this);
