// Generated by CoffeeScript 1.10.0
(function() {
  var Normalizer, enforceCommon;

  enforceCommon = require('./enforce-common');

  Normalizer = require('./unicode/Normalizer');

  module.exports = enforceCommon(new Normalizer());

}).call(this);
