// Generated by CoffeeScript 1.9.3
(function() {
  var Normalizer, enforceCommon, unorm;

  unorm = require('unorm');

  enforceCommon = require('./enforce-common');

  Normalizer = require('./unicode/Normalizer');

  module.exports = enforceCommon(new Normalizer(unorm));

}).call(this);
