// Generated by CoffeeScript 1.9.3
(function() {
  var InvalidCodepointError, Precis, PrecisPreparer, ucs2;

  ucs2 = require('punycode').ucs2;

  InvalidCodepointError = require('./error/InvalidCodepointError');

  Precis = require('./constants');

  module.exports = PrecisPreparer = (function() {
    function PrecisPreparer(propertyReader) {
      this.propertyReader = propertyReader;
    }

    PrecisPreparer.prototype.prepare = function(profile, string) {
      var codepoints;
      if (typeof profile.prepare === 'function') {
        return profile.prepare(string);
      }
      codepoints = ucs2.decode(string);
      switch (profile.stringClass) {
        case Precis.STRING_CLASS.FREEFORM:
          this._freeform(codepoints);
          break;
        case Precis.STRING_CLASS.IDENTIFIER:
          this._identifier(codepoints);
          break;
        default:
          throw new Error('PRECIS string class not implemented.');
      }
      return codepoints;
    };

    PrecisPreparer.prototype._freeform = function(codepoints) {
      var category, codepoint, i, isValid, len, results;
      results = [];
      for (i = 0, len = codepoints.length; i < len; i++) {
        codepoint = codepoints[i];
        category = this.propertyReader.precisCategory(codepoint);
        isValid = category === Precis.PRECIS_CATEGORY.PVALID || category === Precis.PRECIS_CATEGORY.FREE_PVAL;
        if (!isValid) {
          throw new InvalidCodepointError("The codepoint " + codepoint + " is not allowed in the 'FreeformClass' string class.");
        } else {
          results.push(void 0);
        }
      }
      return results;
    };

    PrecisPreparer.prototype._identifier = function(codepoints) {
      var category, codepoint, i, len, results;
      results = [];
      for (i = 0, len = codepoints.length; i < len; i++) {
        codepoint = codepoints[i];
        category = this.propertyReader.precisCategory(codepoint);
        if (category !== Precis.PRECIS_CATEGORY.PVALID) {
          throw new InvalidCodepointError("The codepoint " + codepoint + " is not allowed in the 'IdentifierClass' string class.");
        } else {
          results.push(void 0);
        }
      }
      return results;
    };

    return PrecisPreparer;

  })();

}).call(this);
