// Generated by CoffeeScript 1.10.0
(function() {
  var EmptyStringError,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  module.exports = EmptyStringError = (function(superClass) {
    extend(EmptyStringError, superClass);

    function EmptyStringError() {
      this.message = 'String cannot be empty.';
    }

    return EmptyStringError;

  })(Error);

}).call(this);
