// Generated by CoffeeScript 1.9.3
(function() {
  var InvalidDirectionalityError,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  module.exports = InvalidDirectionalityError = (function(superClass) {
    extend(InvalidDirectionalityError, superClass);

    function InvalidDirectionalityError() {
      this.message = 'String violates the directionality rule.';
    }

    return InvalidDirectionalityError;

  })(Error);

}).call(this);
