#!/usr/bin/env bash

set -e

if [ "$1" = "" ]; then scripts/lint; fi

mkdir -p coverage
node_modules/.bin/mocha --require coffee-coverage/register-istanbul "${1-test/suite}"
node_modules/.bin/istanbul report
