#!/usr/bin/env bash
set -e

echo "Fetching UCD"

mkdir -p build/ucd
curl -L http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip -o build/ucd/ucd.zip
# curl -L http://www.unicode.org/Public/8.0.0/ucd/UCD.zip -o build/ucd/ucd.zip
